# Generated by Django 4.2.1 on 2023-06-10 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='made_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
