# Generated by Django 4.2.2 on 2023-06-06 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
    ]
