# Generated by Django 4.2.2 on 2023-06-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_dev_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('Лабораторная', 'Лабораторная'), ('Тест', 'Тест'), ('РГР', 'РГР'), ('Екзамен', 'Екзамен'), ('курсовая', 'курсовая')], max_length=50),
        ),
    ]
