# Generated by Django 4.2.1 on 2023-06-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subject',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('Лабораторная', 'Лабораторная'), ('Тест', 'Тест'), ('РГР', 'РГР'), ('Іспит', 'Іспит'), ('курсова робота', 'курсова робота')], max_length=50),
        ),
    ]
